#Specify the version of nodejs.
# FROM zenato/puppeteer-renderer
#FROM dayyass/muse_as_service:1.1.2
FROM ubuntu:14.04

# RUN rm /etc/apt/sources.list.d/google.list
RUN apt-get update

# RUN cat /etc/os-release

RUN apt-get install -y \
    fonts-noto-cjk locales

RUN sudo apt-get -y install nodejs npm

RUN locale-gen zh_TW.UTF-8  
ENV LC_ALL=zh_TW.UTF-8

RUN mkdir -p /app/
RUN mkdir -p /1.input/
RUN mkdir -p /2.output/

RUN apt-get install git sudo -y

# --------------
RUN sudo apt-get install -y autoconf automake libtool
RUN sudo apt-get install -y libpng-dev
RUN sudo apt-get install -y libjpeg-dev
RUN sudo apt-get install -y g++
RUN sudo apt-get install -y libtiff-dev
RUN sudo apt-get install -y libopencv-dev libtesseract-dev
RUN sudo apt-get install -y git
RUN sudo apt-get install -y cmake
RUN sudo apt-get install -y build-essential
RUN sudo apt-get install -y libleptonica-dev
RUN sudo apt-get install -y liblog4cplus-dev
RUN sudo apt-get install -y libcurl3-dev
RUN sudo apt-get install -y python2.7-dev
RUN sudo apt-get install -y Tk8.5 
RUN sudo apt-get install -y Tcl8.5 

RUN sudo apt-get install -y tk8.6-dev 
RUN sudo apt-get install -y tcl8.6-dev
# RUN sudo apt-get build-dep -y python-imaging --fix-missing
RUN sudo apt-get install -y imagemagick
# Build Leptonica
RUN apt-get install -y wget
RUN wget https://github.com/DanBloomberg/leptonica/releases/download/1.74.3/leptonica-1.74.3.tar.gz
RUN tar -zxvf leptonica-1.74.3.tar.gz
WORKDIR /leptonica-1.74.3/
RUN ./autobuild
RUN ./configure
RUN make
RUN sudo make install
RUN sudo ldconfig
# Build Tesseract

WORKDIR /
RUN wget https://github.com/tesseract-ocr/tesseract/archive/refs/tags/5.2.0.tar.gz
RUN tar -zxvf 5.2.0.tar.gz
# RUN ls /
WORKDIR /tesseract-5.2.0/
RUN ./autogen.sh
RUN sudo apt-get install python-software-properties -y
RUN sudo apt-get install software-properties-common -y
RUN sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
RUN sudo apt-get update
RUN sudo apt-get install -y gcc-8 g++-8
RUN gcc -v
RUN ./configure
RUN make
RUN sudo make install
RUN sudo ldconfig
# Set Environment Variable
RUN TESSDATA_PREFIX=/usr/local/share/
# Download the relevant Tesseract English Language Packages
WORKDIR /
RUN wget https://tesseract-ocr.googlecode.com/files/tesseract-ocr-3.02.eng.tar.gz
RUN tar -xf tesseract-ocr-3.02.eng.tar.gz
RUN sudo cp -r tesseract-ocr/tessdata $TESSDATA_PREFIX

RUN apt-get install tesseract-ocr -y

COPY package.json /
RUN npm i



CMD ["node", "/app/index.js"]