# docker-Specify the compose version
version: "3"

services:
  # imgCrop:
  #   build: Dockerfile-imgCrop
  app:
    build: .
    tty: true
    volumes: 
      - ./app:/app/
      - ./1.input:/1.input/
      - ./2.output:/2.output/
      - ./3.cache:/3.cache/
  crop:
    build: 
      context: .
      dockerfile: Dockerfile_crop
    tty: true
    volumes: 
      - ./app:/app/
      - ./2.output:/2.output/
      - ./3.cache:/3.cache/